In [9]:
# for imports
import os, sys

current_path = os.getcwd().split('datasets-preporation')[0]+'datasets-preporation'
sys.path.append(current_path)

In [1]:
import kagglehub

path = kagglehub.dataset_download("hemishveeraboina/aime-problem-set-1983-2024")

print("Path to dataset files:", path)

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Path to dataset files: /Users/23108022/.cache/kagglehub/datasets/hemishveeraboina/aime-problem-set-1983-2024/versions/1

In [14]:
import pandas as pd

dataset_name = "AIME_Dataset_1983_2024"
df = pd.read_csv(path + f"/{dataset_name}.csv")
df

,ID,Year,Problem Number,Question,Answer,Part
0,1983-1,1983,1,"Let $x$ , $y$ and $z$ all exceed $1$ and let $...",60,NaN
1,1983-2,1983,2,"Let $f(x)=|x-p|+|x-15|+|x-p-15|$ , where $0 < ...",15,NaN
2,1983-3,1983,3,What is the product of the real roots of the e...,20,NaN
3,1983-4,1983,4,A machine-shop cutting tool has the shape of a...,26,NaN
4,1983-5,1983,5,Suppose that the sum of the squares of two com...,4,NaN
...,...,...,...,...,...,...
928,2024-II-11,2024,11,Find the number of triples of nonnegative inte...,601,II
929,2024-II-12,2024,12,"Let $O(0,0),A(\tfrac{1}{2},0),$ and $B(0,\tfra...",23,II
930,2024-II-13,2024,13,Let $\omega\neq 1$ be a 13th root of unity. Fi...,321,II
931,2024-II-14,2024,14,Let $b \geq 2$ be an integer. Call a positive ...,211,II
932,2024-II-15,2024,15,Find the number of rectangles that can be form...,315,II

In [10]:
df_qa = df[['Question', 'Answer']]
df_qa

                                              Question Answer
0    Let $x$ , $y$ and $z$ all exceed $1$ and let $...     60
1    Let $f(x)=|x-p|+|x-15|+|x-p-15|$ , where $0 < ...     15
2    What is the product of the real roots of the e...     20
3    A machine-shop cutting tool has the shape of a...     26
4    Suppose that the sum of the squares of two com...      4
..                                                 ...    ...
928  Find the number of triples of nonnegative inte...    601
929  Let $O(0,0),A(\tfrac{1}{2},0),$ and $B(0,\tfra...     23
930  Let $\omega\neq 1$ be a 13th root of unity. Fi...    321
931  Let $b \geq 2$ be an integer. Call a positive ...    211
932  Find the number of rectangles that can be form...    315

[933 rows x 2 columns]

In [11]:
from dp.datasets.core.constants import QUESTION_COLUMN, ANSWER_COLUMNS

df_qa.columns = [QUESTION_COLUMN, ANSWER_COLUMNS]
df_qa

                                              question answer
0    Let $x$ , $y$ and $z$ all exceed $1$ and let $...     60
1    Let $f(x)=|x-p|+|x-15|+|x-p-15|$ , where $0 < ...     15
2    What is the product of the real roots of the e...     20
3    A machine-shop cutting tool has the shape of a...     26
4    Suppose that the sum of the squares of two com...      4
..                                                 ...    ...
928  Find the number of triples of nonnegative inte...    601
929  Let $O(0,0),A(\tfrac{1}{2},0),$ and $B(0,\tfra...     23
930  Let $\omega\neq 1$ be a 13th root of unity. Fi...    321
931  Let $b \geq 2$ be an integer. Call a positive ...    211
932  Find the number of rectangles that can be form...    315

[933 rows x 2 columns]

In [16]:
df_qa.to_json(f'{dataset_name}_prepared.jsonl', orient='records', lines=True)